export const experience = [
  {
    company: "FloQast",
    title: "Software Engineer Intern",
    startDate: "June 2025",
    endDate: "August 2025",
    description: [
      "Joined the Close Automation team where I worked on the journal entry management feature",
      "Built and shipped the Actions View feature to improve workflow tracking efficiency and provide instant task visibility",
      "Delivered a multitude of frontend enhancements in React/JavaScript to address user feedback and drive product improvements",
      "Collaborated with product and design teams in an agile environment using Jira and Git",
    ],
    stack: [
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "MongoDB",
      "Jest",
      "Vitest",
      "Jira",
      "Git",
    ],
    link: "https://floqast.com",
  },
  {
    company: "PRIME Lab",
    title: "Undergraduate Researcher",
    startDate: "Feb 2024",
    endDate: "Jan 2025",
    description: [
      "Researched human-AI collaboration, programming tools, and real-time educational data analysis, mentored by Dr. Yan Chen",
      "Performed data analysis using PostgreSQL and SQL, revealing engagement patterns that contributed to research presented at CHI 2025 conference",
      "Developed a web automation system powered by an AI-generated persona modeled on user personality traits",
      "Designed and conducted user studies to evaluate the effectiveness of different AI systems",
    ],
    stack: [
      "React",
      "JavaScript",
      "Python",
      "Flask",
      "PostgreSQL",
      "SQL",
      "Git",
    ],
    link: "https://chensivan.github.io/",
  },
];
